[package]
name = "cv_generator"
version = "0.1.1-beta.14"
description = ""
authors = [ "Antoine Barbier <antoine.c.barbier@frog.co>" ]
license = ""
repository = ""
default-run = "cv_generator"
edition = "2021"
rust-version = "1.60"

[build-dependencies.tauri-build]
version = "1.5.2"
features = [ ]

[dependencies]
window-vibrancy = "0.4" #Use version 0.4 for tauri v1

  [dependencies.serde]
  version = "1.0"
  features = [ "derive" ]

  [dependencies.tauri]
  version = "1.6.5"
  features = [
  "fs-rename-file",
  "fs-remove-file",
  "updater",
  "shell-sidecar",
  "shell-open",
  "protocol-asset",
  "window-maximize",
  "window-close",
  "window-start-dragging",
  "window-minimize",
  "window-hide",
  "window-unmaximize",
  "window-unminimize",
  "window-show",
  "macos-private-api",
  "dialog-all",
  "http-all",
  "fs-read-dir",
  "fs-exists",
  "fs-read-file",
  "fs-create-dir",
  "fs-write-file",
  "path-all"
]

  [dependencies.tauri-plugin-store]
  git = "https://github.com/tauri-apps/plugins-workspace"
  branch = "v1"

[features]
custom-protocol = [ "tauri/custom-protocol" ]
