[package]
name = "ts-const-enums"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = { version = "1.0", features = ["proc-macro"] }
deluxe = "0.5.0"
ts-rs = { version = "9.0.1" }
convert_case = "0.6.0"